// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH5zGlFXT5aeQ1WGE_SWUSF9pzFM_bZxk',
    appId: '1:1088220632406:android:d4ca9e9004af1def93b2f7',
    messagingSenderId: '1088220632406',
    projectId: 'fcm4flutter-d46fa',
    storageBucket: 'fcm4flutter-d46fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD2dYg_SCIuhdsUTOcY2Th_TQFM3F_ip8',
    appId: '1:1088220632406:ios:06df6342b60b601193b2f7',
    messagingSenderId: '1088220632406',
    projectId: 'fcm4flutter-d46fa',
    storageBucket: 'fcm4flutter-d46fa.appspot.com',
    iosBundleId: 'com.example.fcm.msg',
  );
}
